; COR24 Assembly - Generated by wasm2cor24
; Supports: i32.add, i32.sub, i32.and, i32.or, i32.xor
;           i32.const, local.get, local.set

; Function: main
; Signature: () -> void
main:
        push    fp
        mov     fp, sp
        add     sp, -3
        lc      r0, 0
        sw      r0, 0(fp)
.L0:
        lc      r0, 0
        lw      r1, 0(fp)
        la      r2, 0xFF0000
        add     r0, r2
        sb      r1, 0(r0)
        lw      r0, 0(fp)
        lc      r1, 1
        add     r0, r1
        sw      r0, 0(fp)
        bra     .L0
.L1:
        mov     sp, fp
        pop     fp
        halt                ; return (use jmp (r1) for real calls)

; Function: add
; Signature: (I32, I32) -> I32
add:
        push    fp
        mov     fp, sp
        add     sp, -6
        sw      r0, 0(fp)
        sw      r1, 3(fp)
        lw      r0, 3(fp)
        lw      r1, 0(fp)
        add     r0, r1
        mov     sp, fp
        pop     fp
        halt                ; return (use jmp (r1) for real calls)

